# site settings
title: TCSG Limited
subtitle: Software Consulting
email: tom@tcsg.uk
description: Providing professional software solutions for your business
baseurl: "" # the subpath of your site, e.g. /blog
url: https://tcsg.uk # the base hostname & protocol for your site
author: Tom Garbutt
street_address: TCSG Limited, 13b The Vale
city: London
# state: TN
zip_code: W3 7SH
country: United Kingdom
# phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: 
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/tomgarbutt
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
